### ISSUE TITLE
feat(e2e): support for single test-suit and single test-case execution

### ISSUE THREAD

**Issue by kirchoni** [telerik/kendo-react-tasks#32]
With our codebase growing, the execution time of the `e2e-tests `increase, so we'll need an option to run at least a single file(or even better - a single test-case), rather than all `e2e-tests` found in the repo. I'm suggesting an implementation in `nightwatch-cli-args` branch, but i suspect further improvements may be applied, since my knowledge with command-line-arguments are limited.
cc @mitagg

**Comment by mitagg** [comment]
In order to take advantage of the [command line arguments](http://nightwatchjs.org/guide) provided by Nightwatch, simply pass them to the child process - 

`const nightwatchProcess = spawn(path.resolve(command), [ '-c', path.join(__dirname, './nightwatch.conf.js'), ...process.argv.slice(3) ]);`

Just strip the first [three parameters from the current process](https://nodejs.org/docs/latest/api/process.html#process_process_argv), the rest will be the user-defined ones.
